### ISSUE TITLE
ListView ItemCheck & ItemChecked event

### ISSUE THREAD

**Issue by ngoedde** [SDClowen/SDUI#4]
Currently, there is no proper support for Checkbox ListViews (ListView.CheckBoxes = true) because the events won't be fired.

**Comment by SDClowen** [comment]
Tested working

![image](https://user-images.githubusercontent.com/14323838/166126271-e8166eb3-ba02-4958-919e-668ab70cc830.png)

![image](https://user-images.githubusercontent.com/14323838/166126279-b16f36e8-cd4d-424d-ac85-8dbba3ca7468.png)

![image](https://user-images.githubusercontent.com/14323838/166126294-b10190d1-1335-46f3-9503-a70781a46199.png)
