### ISSUE TITLE
TextBox UseSystemPasswordChar = true özellikli textbox kontrolü seçildiğinde otomatik UseSystemPasswordChar = false yapma özelliği eklenebilir

### ISSUE THREAD

**Issue by EvilNiqht** [SDClowen/SDUI#9]
https://github.com/SDClowen/SDUI/blob/1eab72be44050f47dd02d12ff39007c810f2e798/SDUI/Controls/TextBox.cs#L100

Aşağıdaki kodlar eklenirse çok tatlı olur şifre girilirken yada bakmak için ayrı ayrı gizle göster butonlarını eklemeye ve basmaya gerek kalmaz;

        private bool _passFocusShow = false;
        public bool PassFocusShow
        {
            get { return _passFocusShow; }
            set
            {
                _passFocusShow = value;
                Invalidate();
            }
        }
        protected override void OnEnter(System.EventArgs e)
        {
            if (UseSystemPasswordChar && PassFocusShow) _textBox.UseSystemPasswordChar = false;  
        }
        protected override void OnLeave(System.EventArgs e)
        {
            if (UseSystemPasswordChar && PassFocusShow) _textBox.UseSystemPasswordChar = UseSystemPasswordChar;
        }

**Comment by SDClowen** [comment]
Eklendi. Katkınız için teşekkürler.
